# Generated by Django 4.1.3 on 2022-12-01 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="City")),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Name in URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=88,
                        verbose_name="Day",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            12,
                            1,
                            22,
                            59,
                            21,
                            109085,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Sunny", "Sunny"),
                            ("Partially cloudy", "Partially cloudy"),
                            ("Cloudy", "Cloudy"),
                            ("Overcast", "Overcast"),
                            ("Rainy", "Rainy"),
                            ("Drizzle", "Drizzle"),
                            ("Snowy", "Snowy"),
                            ("Stormy", "Stormy"),
                            ("Tornadoes", "Tornadoes"),
                            ("Thundersnow", "Thundersnow"),
                            ("Thunderstorm", "Thunderstorm"),
                            ("Fog", "Fog"),
                            ("Hurricanes", "Hurricanes"),
                            ("Sandstorms", "Sandstorms"),
                        ],
                        max_length=88,
                        verbose_name="Weather status",
                    ),
                ),
                ("temperature", models.IntegerField(verbose_name="Temperature")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "verbose_name": "Day",
                "verbose_name_plural": "Days",
            },
        ),
        migrations.CreateModel(
            name="Hours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "this_hour_status",
                    models.CharField(
                        choices=[
                            ("Sunny", "Sunny"),
                            ("Partially cloudy", "Partially cloudy"),
                            ("Cloudy", "Cloudy"),
                            ("Overcast", "Overcast"),
                            ("Rainy", "Rainy"),
                            ("Drizzle", "Drizzle"),
                            ("Snowy", "Snowy"),
                            ("Stormy", "Stormy"),
                            ("Tornadoes", "Tornadoes"),
                            ("Thundersnow", "Thundersnow"),
                            ("Thunderstorm", "Thunderstorm"),
                            ("Fog", "Fog"),
                            ("Hurricanes", "Hurricanes"),
                            ("Sandstorms", "Sandstorms"),
                        ],
                        max_length=88,
                        verbose_name="This hour status",
                    ),
                ),
                ("day_hours", models.IntegerField(verbose_name="Hour")),
                (
                    "temperature",
                    models.IntegerField(verbose_name="Temperature of this hour"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.city",
                        verbose_name="The weather today",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_hours",
                        to="weather.day",
                        verbose_name="The weather status of today",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hour",
                "verbose_name_plural": "Hours",
            },
        ),
    ]
