# Generated by Django 4.1.3 on 2022-12-01 23:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 1, 23, 24, 58, 675731, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="hours",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="weather.city",
                verbose_name="City",
            ),
        ),
    ]
